experiment_name: ames-price-mini
model:
  type: RandomForestRegressor
  params:
    n_estimators: 300
    max_depth: 18
    random_state: 42
train:
  test_size: 0.2
  random_state: 42
mlflow:
  tracking_uri: http://localhost:5555
  registered_model_name: ames_price_rf
